#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

CLOUD_VARS_FILE="$SCRIPT_DIR/cloud_variables.env"

log() {
  printf '\n[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

load_cloud_variables() {
  if [[ -f "$CLOUD_VARS_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CLOUD_VARS_FILE"
  fi
}

save_cloud_variables() {
  export PROJECT_ID REGION INSTANCE DB_NAME DB_USER FIRESTORE_DB APP_SERVICE APP_SA SYNC_FUNCTION ANALYTICS_FUNCTION APP_USER_ID INITIAL_SYNC_DAYS LOOKER_ENABLED LOOKER_DB_USER ENABLE_LOOKER_AUTH_NETWORK INSTANCE_CONNECTION_NAME APP_URL SYNC_URL ANALYTICS_URL
  python3 - "$CLOUD_VARS_FILE" <<'PY'
import os, shlex, sys
path = sys.argv[1]
keys = [
    "PROJECT_ID", "REGION", "INSTANCE", "DB_NAME", "DB_USER", "FIRESTORE_DB",
    "APP_SERVICE", "APP_SA", "SYNC_FUNCTION", "ANALYTICS_FUNCTION", "APP_USER_ID",
    "INITIAL_SYNC_DAYS", "LOOKER_ENABLED", "LOOKER_DB_USER", "ENABLE_LOOKER_AUTH_NETWORK",
    "INSTANCE_CONNECTION_NAME", "APP_URL", "SYNC_URL", "ANALYTICS_URL"
]
with open(path, "w", encoding="utf-8") as f:
    f.write("# Generated by install_gcloud.sh. Safe to source.\n")
    for key in keys:
      value = os.environ.get(key, "")
      f.write(f"{key}={shlex.quote(value)}\n")
PY
}

prompt_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-}"
  local value=""

  while true; do
    if [[ -n "$default_value" ]]; then
      read -r -p "$prompt_text [$default_value]: " value || true
    else
      read -r -p "$prompt_text: " value || true
    fi
    value="${value:-$default_value}"
    [[ -n "$value" ]] || { echo "Value is required."; continue; }
    printf -v "$var_name" '%s' "$value"
    return 0
  done
}

prompt_project_id() {
  local default_value="${1:-}"
  local value=""
  while true; do
    if [[ -n "$default_value" ]]; then
      read -r -p "Google Cloud project ID [$default_value]: " value || true
    else
      read -r -p "Google Cloud project ID: " value || true
    fi
    value="${value:-$default_value}"
    [[ -n "$value" ]] || { echo "Value is required."; continue; }
    if gcloud projects describe "$value" >/dev/null 2>&1; then
      PROJECT_ID="$value"
      return 0
    fi
    echo "Project '$value' was not found or is not accessible with your current gcloud account."
  done
}

prompt_yes_no() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="${3:-Y}"
  local value=""
  while true; do
    read -r -p "$prompt_text [${default_value}/n]: " value || true
    value="${value:-$default_value}"
    case "$value" in
      Y|y|yes|YES) printf -v "$var_name" '%s' "yes"; return 0 ;;
      N|n|no|NO) printf -v "$var_name" '%s' "no"; return 0 ;;
      *) echo "Enter Y or n." ;;
    esac
  done
}

resource_exists() {
  "$@" >/dev/null 2>&1
}

require_cmd gcloud
load_cloud_variables

prompt_project_id "${PROJECT_ID:-}"
prompt_default REGION "Region" "${REGION:-us-central1}"
prompt_default INSTANCE "Cloud SQL instance name" "${INSTANCE:-cve-analyzer-sql}"
prompt_default DB_NAME "PostgreSQL database name" "${DB_NAME:-cve_analyzer}"
prompt_default DB_USER "PostgreSQL app user" "${DB_USER:-appuser}"
prompt_default FIRESTORE_DB "Firestore database ID" "${FIRESTORE_DB:-cve-analyzer}"
prompt_default APP_SERVICE "Cloud Run service name" "${APP_SERVICE:-cve-analyzer-app}"
prompt_default APP_SA "Service account name" "${APP_SA:-cve-analyzer-sa}"
prompt_default SYNC_FUNCTION "Sync function name" "${SYNC_FUNCTION:-syncRecentCves}"
prompt_default ANALYTICS_FUNCTION "Analytics function name" "${ANALYTICS_FUNCTION:-refreshTrendAnalytics}"
prompt_default APP_USER_ID "Demo app user ID" "${APP_USER_ID:-demo-user}"
prompt_yes_no DELETE_LOCAL_CONFIG "Delete local cloud_variables.env and .cve_runtime files after uninstall" "Y"

save_cloud_variables

log "Active project: $PROJECT_ID"
gcloud config set project "$PROJECT_ID" >/dev/null

cat <<OUT
This deletes these resources from project '$PROJECT_ID':
  - Cloud Run service: $APP_SERVICE
  - Cloud Function: $SYNC_FUNCTION
  - Cloud Function: $ANALYTICS_FUNCTION
  - Cloud SQL instance: $INSTANCE
  - Firestore database: $FIRESTORE_DB
  - Service account: ${APP_SA}@${PROJECT_ID}.iam.gserviceaccount.com
OUT

echo
read -r -p "Type DELETE to continue: " CONFIRM
[[ "$CONFIRM" == "DELETE" ]] || fail "Cancelled."

log "Deleting Cloud Run service"
if resource_exists gcloud run services describe "$APP_SERVICE" --project "$PROJECT_ID" --region "$REGION"; then
  gcloud run services delete "$APP_SERVICE" --project "$PROJECT_ID" --region "$REGION" --quiet
fi

log "Deleting Cloud Functions"
if resource_exists gcloud functions describe "$SYNC_FUNCTION" --project "$PROJECT_ID" --gen2 --region "$REGION"; then
  gcloud functions delete "$SYNC_FUNCTION" --project "$PROJECT_ID" --gen2 --region "$REGION" --quiet
fi
if resource_exists gcloud functions describe "$ANALYTICS_FUNCTION" --project "$PROJECT_ID" --gen2 --region "$REGION"; then
  gcloud functions delete "$ANALYTICS_FUNCTION" --project "$PROJECT_ID" --gen2 --region "$REGION" --quiet
fi

log "Deleting Cloud SQL instance"
if resource_exists gcloud sql instances describe "$INSTANCE" --project "$PROJECT_ID"; then
  gcloud sql instances patch "$INSTANCE" --project "$PROJECT_ID" --no-deletion-protection --quiet >/dev/null 2>&1 || true
  gcloud sql instances delete "$INSTANCE" --project "$PROJECT_ID" --quiet
fi

log "Deleting Firestore database"
if resource_exists gcloud firestore databases describe --project "$PROJECT_ID" --database "$FIRESTORE_DB"; then
  gcloud firestore databases update --project "$PROJECT_ID" --database "$FIRESTORE_DB" --no-delete-protection --quiet >/dev/null 2>&1 || true
  gcloud firestore databases delete --project "$PROJECT_ID" --database "$FIRESTORE_DB" --quiet
fi

log "Deleting service account"
SERVICE_ACCOUNT_EMAIL="${APP_SA}@${PROJECT_ID}.iam.gserviceaccount.com"
if resource_exists gcloud iam service-accounts describe "$SERVICE_ACCOUNT_EMAIL" --project "$PROJECT_ID"; then
  gcloud iam service-accounts delete "$SERVICE_ACCOUNT_EMAIL" --project "$PROJECT_ID" --quiet
fi

if [[ "$DELETE_LOCAL_CONFIG" == "yes" ]]; then
  rm -f "$CLOUD_VARS_FILE"
  rm -rf "$SCRIPT_DIR/.cve_runtime"
fi

log "Uninstall complete."
